### ISSUE TITLE
Make it possible to set a custom $host

### ISSUE THREAD

**Issue by thomasmaas** [3scale/3scale_ws_api_for_php#19]
It should fallback to DEFAULT_ROOT_ENDPOINT but needs to be overridable when initializing client

https://github.com/3scale/3scale_ws_api_for_php/blob/master/lib/ThreeScaleClient.php#L24

**Comment by VinayBhalerao** [comment]
Closed via https://github.com/3scale/3scale_ws_api_for_php/pull/21
