### ISSUE TITLE
Unable to set '#' on the Reporting metrics

### ISSUE THREAD

**Issue by ericseanturner** [3scale/3scale_ws_api_for_php#8]
For the Reporting API, as seen in the docs, I should be able to pass in '#' with the value in the usage array as below. Instead the PHP SDK encodes '#' into %23 and the call fails.

'usage'      => array(
                                                        'myMetric' => '#25', 
                                                             )

**Comment by VinayBhalerao** [comment]
Closing per https://github.com/3scale/3scale_ws_api_for_php/issues/8#issuecomment-66444557
